const tabs=[['coach','Coach'],['lessons','40 Lessons'],['phrasebook','Phrasebook'],['quiz','Quiz'],['native','Native Audio']];
const P=[
['p001','pap','Start','Bon dia.','Good morning.','bone DEE-ah'],['p002','pap','Start','Bon tardi.','Good afternoon.','bone TAR-dee'],['p003','pap','Start','Bon nochi.','Good evening.','bone NO-chee'],['p004','pap','Start','Kon ta bai?','How are you?','kohn tah BYE'],['p005','pap','Start','Mi ta bon.','I am good.','mee tah bone'],
['p006','pap','Polite','Por fabor.','Please.','por fah-BOR'],['p007','pap','Polite','Danki.','Thank you.','DAHN-kee'],['p008','pap','Polite','Di nada.',"You're welcome.",'dee NAH-dah'],['p009','pap','Polite','Mi no ta komprendé.',"I don’t understand.",'mee noh tah kom-pren-DAY'],['p010','pap','Polite','Bo por ripití?','Can you repeat?','boh por ree-pee-TEE'],
['p011','pap','Airport','Mi tin un reservashon.','I have a reservation.','mee tin oon reh-ser-vah-SHOWN'],['p012','pap','Airport','Unda ta e salida?','Where is the exit?','OON-dah tah eh sah-LEE-dah'],['p013','pap','Airport','Mi maleta a pèrdè.','My suitcase is lost.','mee mah-LEH-tah ah PER-deh'],['p014','pap','Airport','Mi ta buska un taxi.',"I’m looking for a taxi.",'mee tah BOOS-kah oon taxi'],
['p015','pap','Taxi','Kuantu e ta kustá?','How much does it cost?','KWAN-too eh tah koos-TAH'],['p016','pap','Taxi','Llevami na hotel.','Take me to the hotel.','yeh-VAH-mee nah hotel'],['p017','pap','Taxi','Mi ke bai Playa Kenepa.','I want to go to Kenepa Beach.','mee keh BYE PLY-ah keh-NEH-pah'],['p018','pap','Taxi','Direito.','Straight.','dee-RAY-toh'],['p019','pap','Taxi','Na man drechi.','Right.','nah mahn DREH-chee'],['p020','pap','Taxi','Na man robes.','Left.','nah mahn ROH-bess'],
['p021','pap','Hotel','Mi nomber ta Rayna.','My name is Rayna.','mee NOM-ber tah Rayna'],['p022','pap','Hotel','Mi ke un kamber ku dos kama.','I want a room with two beds.','mee keh oon KAM-ber koo dose KAH-mah'],['p023','pap','Hotel','Mi a papia ku Stephanie di e Concierge team.','I spoke with Stephanie from the Concierge team.','mee ah PAH-pyah koo Stephanie dee eh concierge team'],['p024','pap','Hotel','Mi a papia ku Tai Rock tambe.','I also spoke with Tai Rock.','mee ah PAH-pyah koo Tai Rock tahm-BAY'],['p025','pap','Hotel','Bo por yuda mi?','Can you help me?','boh por YOO-dah mee'],['p026','pap','Hotel','Mi tin un problema.','I have a problem.','mee tin oon pro-BLAY-mah'],['p027','pap','Hotel','Mi no ta haña e lugá.',"I can’t find the place.",'mee noh tah HAH-nyah eh loo-GAH'],
['p028','pap','Restaurant','Mi ke pidi.','I want to order.','mee keh PEE-dee'],['p029','pap','Restaurant','Menu, por fabor.','Menu, please.','meh-NOO, por fah-BOR'],['p030','pap','Restaurant','Bon provecho.','Enjoy your meal.','bone proh-VAY-choh'],['p031','pap','Restaurant','Nos tin un reservashon.','We have a reservation.','nohs tin oon reh-ser-vah-SHOWN'],['p032','pap','Restaurant','Kiko bo ta rekomendá?','What do you recommend?','KEE-koh boh tah reh-koh-men-DAH'],['p033','pap','Restaurant','La cuenta, por fabor.','The bill, please.','lah KWEN-tah, por fah-BOR'],
['p034','pap','Drinks','Mi ke un Hugo Spritz ku hopi mint.','I would like a Hugo Spritz with lots of mint.','mee keh oon HOO-go spritz koo HOH-pee mint'],['p035','pap','Drinks','Mi ke un French 79, por fabor.','I would like a French 79, please.','mee keh oon French seventy-nine, por fah-BOR'],['p036','pap','Drinks','Bo tin Caymus?','Do you have Caymus?','boh tin KAY-mus'],['p037','pap','Drinks','Bo tin Woodford Double Oaked?','Do you have Woodford Double Oaked?','boh tin Woodford Double Oaked'],
['p038','pap','Beach','Silla di playa.','Beach chair.','SEE-yah dee PLY-ah'],['p039','pap','Beach','Sombré.','Umbrella.','som-BRAY'],['p040','pap','Beach','Snorkel.','Snorkel.','snorkel'],['p041','pap','Beach','Nos tin un les di snorkel na Playa Piskado.','We have a snorkeling lesson at Playa Piskado.','nohs tin oon less dee snorkel nah PLY-ah pees-KAH-doh'],['p042','pap','Beach','Nos tin les di mermaid na dies or di mainta.','We have mermaid lessons at 10 in the morning.','nohs tin less dee mermaid nah dees or dee MYN-tah'],
['p043','pap','Birthday','Nos ta selebrá cumpleaño di mi yiu Riley ku ta bira 11.',"We are celebrating my daughter Riley’s 11th birthday.",'nohs tah seh-leh-BRAH koom-play-AH-nyoh dee mee yoo Riley koo tah BEE-rah eleven'],['p044','pap','Birthday','Nos ta selebrá cumpleaño di mi sobrina Harper ku ta bira 10.',"We are celebrating my niece Harper’s 10th birthday.",'nohs tah seh-leh-BRAH koom-play-AH-nyoh dee mee soh-BREE-nah Harper koo tah BEE-rah ten'],['p045','pap','Birthday','Felis cumpleaño, Ry Ry.','Happy birthday, Ry Ry.','feh-LEES koom-play-AH-nyoh Ry Ry'],
['p046','pap','Emergency','Mi tin dolor.','I have pain.','mee tin doh-LOR'],['p047','pap','Emergency','Mi mester un dòkter.','I need a doctor.','mee MES-ter oon DOK-ter'],['p048','pap','Emergency','Mi a pèrdè mi pasaporte.','I lost my passport.','mee ah PER-deh mee pah-sah-POR-teh'],['p049','pap','Emergency','Mi ke reportá un robo.','I want to report a theft.','mee keh reh-por-TAH oon ROH-boh'],['p050','pap','Emergency','Yama ambulans, por fabor.','Call an ambulance, please.','YAH-mah am-boo-LANS por fah-BOR'],
['p051','nl-NL','Dutch','Goedemorgen.','Good morning.','Goedemorgen.'],['p052','nl-NL','Dutch','Dank u.','Thank you.','Dank u.'],['p053','nl-NL','Dutch','Alstublieft.','Please.','Alstublieft.'],['p054','nl-NL','Dutch','Waar is de uitgang?','Where is the exit?','Waar is de uitgang?'],
['p055','es-ES','Spanish','Buenos dias.','Good morning.','Buenos dias.'],['p056','es-ES','Spanish','Por favor.','Please.','Por favor.'],['p057','es-ES','Spanish','Gracias.','Thank you.','Gracias.'],['p058','es-ES','Spanish','Que recomienda?','What do you recommend?','Que recomienda?']
].map(x=>({id:x[0],lang:x[1],cat:x[2],pap:x[3],eng:x[4],sound:x[5]}));
const L=[['Greetings',['p001','p002','p003','p004','p005']],['Polite Survival',['p006','p007','p008','p009','p010']],['Airport',['p011','p012','p013','p014']],['Taxi',['p015','p016','p017','p018','p019','p020']],['Hotel',['p021','p022','p023','p024','p025','p026','p027']],['Dining',['p028','p029','p030','p031','p032','p033']],['Drinks',['p034','p035','p036','p037']],['Beach',['p038','p039','p040','p041','p042']],['Birthday',['p043','p044','p045']],['Emergency',['p046','p047','p048','p049','p050']],['Dutch Basics',['p051','p052','p053','p054']],['Spanish Basics',['p055','p056','p057','p058']]];while(L.length<40)L.push(['Review '+(L.length+1),L[L.length%12][1]]);
const scenarios=[['Airport Arrival',['Airport','Polite','Taxi']],['Hotel and Concierge',['Hotel','Polite','Emergency']],['Drinks and Dining',['Restaurant','Drinks','Polite']],['Taxi and Directions',['Taxi']],['Beach and Excursions',['Beach']],['Birthday Mode',['Birthday']],['Emergency Calm Mode',['Emergency','Dutch','Spanish']]];
let mode=localStorage.mode||'slow',lesson=0,step=0,auto=false,busy=false,score=0;const $=id=>document.getElementById(id), p=id=>P.find(x=>x.id===id)||P[0];
function status(t){$('status').textContent=t} function cap(s){return s[0].toUpperCase()+s.slice(1)}
function setMode(m){mode=m;localStorage.mode=m;['slow','normal','local'].forEach(x=>$('sp'+cap(x)).classList.toggle('active',x===m));status('Speed set to '+m)}
function wait(ms){return new Promise(r=>setTimeout(r,ms))}
function voiceFor(lang){const vs=speechSynthesis.getVoices();let wanted=lang==='pap'?'en-US':lang;return vs.find(v=>v.lang===wanted)||vs.find(v=>v.lang&&v.lang.toLowerCase().startsWith(wanted.split('-')[0].toLowerCase()))||vs.find(v=>v.lang==='en-US')||vs[0]}
function speak(text,rate=.55,lang='en-US'){return new Promise(res=>{if(!window.speechSynthesis){res();return}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.rate=rate;u.lang=lang==='pap'?'en-US':lang;let v=voiceFor(lang);if(v)u.voice=v;u.onend=res;u.onerror=res;status('Playing '+(lang==='pap'?'phonetic fallback':lang)+' voice...');speechSynthesis.speak(u)})}
function mp3(src){return new Promise(res=>{let a=new Audio(src);a.onplay=()=>status('Playing native audio...');a.onended=()=>res(true);a.onerror=()=>res(false);a.play().catch(()=>res(false))})}
async function playPhrase(q){if(busy)return;busy=true;let slow=mode==='slow';let ok=await mp3(`audio/${q.id}_${slow?'slow':'normal'}.mp3`);if(!ok){let text=q.lang==='pap'?q.sound:q.pap;await speak(text,slow?.48:mode==='normal'?.68:.9,q.lang)}if(mode==='slow'){await wait(900);ok=await mp3(`audio/${q.id}_slow.mp3`);if(!ok)await speak(q.lang==='pap'?q.sound:q.pap,.48,q.lang);await wait(800);await speak(q.eng,.62,'en-US');await wait(600);await speak('Your turn. Repeat it now.',.58,'en-US')}else if(mode==='normal'){await wait(450);await speak(q.eng,.72,'en-US')}busy=false}
async function playCurrent(){await playPhrase(p(L[lesson][1][step]));if(auto&&step<L[lesson][1].length-1){step++;renderPlayer();setTimeout(playCurrent,800)}else if(auto){auto=false;status('Lesson complete.')}}
function renderTabs(){ $('tabs').innerHTML=tabs.map(([id,label])=>`<button class="tab ${id==='coach'?'active':''}" onclick="show('${id}',this)">${label}</button>`).join('') }
function show(id,el){document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));if(el)el.classList.add('active');if(id==='quiz')quiz()}
function card(q){return `<div class="phrase"><div class="pap">${q.pap}</div><div class="eng">${q.eng}</div><div class="sound">${q.lang==='pap'?'Sounds like: '+q.sound:'Apple voice route: '+q.lang}</div><div class="note">Native: audio/${q.id}_normal.mp3 / audio/${q.id}_slow.mp3</div><div class="row"><button class="btn" onclick='playPhrase(${JSON.stringify(q)})'>Coach</button><button class="btn secondary" onclick='speak(${JSON.stringify(q.lang==='pap'?q.sound:q.pap)},.48,${JSON.stringify(q.lang)})'>Pronounce</button></div></div>`}
function renderCoach(){ $('coach').innerHTML=`<div class="card"><h2>Choose a trip scenario</h2><p class="big">Dutch, Spanish, and English now route to matching system voices when available. Papiamentu still uses native MP3 first, then phonetic fallback.</p></div><div class="grid scenario-grid">${scenarios.map((s,i)=>`<div class="card"><h3>${s[0]}</h3><p>${s[1].join(', ')}</p><button class="btn" onclick="openScenario(${i})">Open</button></div>`).join('')}</div><div id="scenarioDetail"></div>` }
function openScenario(i){let cats=scenarios[i][1],list=P.filter(q=>cats.includes(q.cat));$('scenarioDetail').innerHTML=`<div class="card"><h2>${scenarios[i][0]}</h2>${list.map(card).join('')}</div>`;$('scenarioDetail').scrollIntoView({behavior:'smooth'})}
function renderLessons(){ $('lessons').innerHTML=`<div class="card"><h2>40 Lesson Player</h2><p class="big">Use Start for auto-advance. Use Repeat / Next / Previous any time.</p></div><div class="grid">${L.map((l,i)=>`<div class="card"><h3>Lesson ${i+1}: ${l[0]}</h3><p>${l[1].map(id=>p(id).pap).slice(0,3).join(' · ')}</p><button class="btn" onclick="openLesson(${i})">Open</button> <button class="btn secondary" onclick="startLesson(${i})">Start</button></div>`).join('')}</div><div id="player"></div>` }
function openLesson(i){lesson=i;step=0;auto=false;renderPlayer();$('player').scrollIntoView({behavior:'smooth'})}
function startLesson(i){lesson=i;step=0;auto=true;renderPlayer();playCurrent();$('player').scrollIntoView({behavior:'smooth'})}
function renderPlayer(){let ids=L[lesson][1],q=p(ids[step]);$('player').innerHTML=`<div class="card"><h2>Lesson ${lesson+1}: ${L[lesson][0]}</h2><div class="playerBox"><span class="pill">Phrase ${step+1} of ${ids.length}</span><div class="pap">${q.pap}</div><div class="eng">${q.eng}</div><div class="sound">${q.lang==='pap'?'Sounds like: '+q.sound:'Voice: '+q.lang}</div><div class="row"><button class="btn secondary" onclick="prev()">Previous</button><button class="btn" onclick="playCurrent()">Repeat</button><button class="btn secondary" onclick="next()">Next</button><button class="btn ${auto?'red':'green'}" onclick="toggleAuto()">${auto?'Stop Auto':'Auto-Advance'}</button></div></div>${ids.map((id,n)=>`<div class="phrase ${n===step?'current':''}"><b>${n+1}.</b> ${p(id).pap}<div class="eng">${p(id).eng}</div></div>`).join('')}</div>`}
function next(){step=Math.min(L[lesson][1].length-1,step+1);renderPlayer()} function prev(){step=Math.max(0,step-1);renderPlayer()} function toggleAuto(){auto=!auto;renderPlayer();if(auto)playCurrent()}
function renderPhrasebook(f=''){let q=f.toLowerCase(),list=P.filter(x=>(x.cat+x.pap+x.eng+x.sound+x.lang).toLowerCase().includes(q));$('phrasebook').innerHTML=`<div class="card"><h2>Phrasebook</h2><input class="search" value="${f}" placeholder="Search taxi, drink, Dutch, Spanish..." oninput="renderPhrasebook(this.value)"></div>${list.map(card).join('')}`}
function quiz(){let q=P[Math.floor(Math.random()*P.length)],opts=[q.eng,...P.filter(x=>x!==q).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.eng)].sort(()=>Math.random()-.5);$('quiz').innerHTML=`<div class="card"><h2>Quiz</h2>${card(q)}<div class="quizChoices">${opts.map(o=>`<button class="choice" onclick="this.classList.add('${o===q.eng?'correct':'wrong'}');${o===q.eng?'score++;setTimeout(quiz,900)':'speak(\'Try again\',.6,\'en-US\')'}">${o}</button>`).join('')}</div><p>Score: ${score}</p></div>`}
function renderNative(){ $('native').innerHTML=`<div class="card"><h2>Native Audio Upgrade</h2><p class="big">Language routing is now: Papiamentu -> native MP3 then phonetic fallback; Dutch -> nl-NL; Spanish -> es-ES; English -> en-US.</p><p>Upload MP3s into /audio/ for best Papiamentu accuracy.</p></div>` }
function init(){renderTabs();renderCoach();renderLessons();renderPhrasebook();renderNative();$('unlockBtn').onclick=()=>speak('Audio is unlocked. Slow mode is on. Welcome to your Curacao language coach.',.52,'en-US');setMode(mode);if(window.speechSynthesis){speechSynthesis.onvoiceschanged=()=>speechSynthesis.getVoices()}}
init();