const tabs=[['coach','Coach'],['lessons','40 Lessons'],['phrasebook','Phrasebook'],['quiz','Quiz'],['native','Native Audio']];
const raw=[
['p001','pap','Start','Bon dia.','Good morning.','Bon dia.'],['p002','pap','Start','Bon tardi.','Good afternoon.','Bon tardi.'],['p003','pap','Start','Bon nochi.','Good evening.','Bon nochi.'],['p004','pap','Start','Kon ta bai?','How are you?','Kon ta bai?'],['p005','pap','Start','Mi ta bon.','I am good.','Mi ta bon.'],
['p006','pap','Polite','Por fabor.','Please.','Por fabor.'],['p007','pap','Polite','Danki.','Thank you.','Danki.'],['p008','pap','Polite','Di nada.',"You're welcome.",'Di nada.'],['p009','pap','Polite','Mi no ta komprende.',"I do not understand.",'Mi no ta komprende.'],['p010','pap','Polite','Bo por ripiti?','Can you repeat?','Bo por ripiti?'],
['p011','pap','Airport','Mi tin un reservashon.','I have a reservation.','Mi tin un reservashon.'],['p012','pap','Airport','Unda ta e salida?','Where is the exit?','Unda ta e salida?'],['p013','pap','Airport','Mi maleta a perde.','My suitcase is lost.','Mi maleta a perde.'],['p014','pap','Airport','Mi ta buska un taxi.',"I am looking for a taxi.",'Mi ta buska un taxi.'],
['p015','pap','Taxi','Kuantu e ta kusta?','How much does it cost?','Kuantu e ta kusta?'],['p016','pap','Taxi','Llevami na hotel.','Take me to the hotel.','Llevami na hotel.'],['p017','pap','Taxi','Mi ke bai Playa Kenepa.','I want to go to Kenepa Beach.','Mi ke bai Playa Kenepa.'],['p018','pap','Taxi','Direito.','Straight.','Direito.'],['p019','pap','Taxi','Na man drechi.','Right.','Na man drechi.'],['p020','pap','Taxi','Na man robes.','Left.','Na man robes.'],
['p021','pap','Hotel','Mi nomber ta Rayna.','My name is Rayna.','Mi nomber ta Rayna.'],['p022','pap','Hotel','Mi ke un kamber ku dos kama.','I want a room with two beds.','Mi ke un kamber ku dos kama.'],['p023','pap','Hotel','Bo por yuda mi?','Can you help me?','Bo por yuda mi?'],['p024','pap','Hotel','Mi tin un problema.','I have a problem.','Mi tin un problema.'],
['p025','pap','Restaurant','Mi ke pidi.','I want to order.','Mi ke pidi.'],['p026','pap','Restaurant','Menu, por fabor.','Menu, please.','Menu, por fabor.'],['p027','pap','Restaurant','Bon provecho.','Enjoy your meal.','Bon provecho.'],['p028','pap','Restaurant','Kiko bo ta rekomenda?','What do you recommend?','Kiko bo ta rekomenda?'],['p029','pap','Restaurant','La cuenta, por fabor.','The bill, please.','La cuenta, por fabor.'],
['p030','pap','Drinks','Mi ke un Hugo Spritz ku hopi mint.','I would like a Hugo Spritz with lots of mint.','Mi ke un Hugo Spritz ku hopi mint.'],['p031','pap','Drinks','Bo tin Caymus?','Do you have Caymus?','Bo tin Caymus?'],['p032','pap','Drinks','Bo tin Woodford Double Oaked?','Do you have Woodford Double Oaked?','Bo tin Woodford Double Oaked?'],
['p033','pap','Beach','Silla di playa.','Beach chair.','Silla di playa.'],['p034','pap','Beach','Sombre.','Umbrella.','Sombre.'],['p035','pap','Beach','Nos tin un les di snorkel na Playa Piskado.','We have a snorkeling lesson at Playa Piskado.','Nos tin un les di snorkel na Playa Piskado.'],
['p036','pap','Birthday','Felis cumpleano, Ry Ry.','Happy birthday, Ry Ry.','Felis cumpleano, Ry Ry.'],['p037','pap','Emergency','Mi tin dolor.','I have pain.','Mi tin dolor.'],['p038','pap','Emergency','Mi mester un dokter.','I need a doctor.','Mi mester un dokter.'],['p039','pap','Emergency','Yama ambulans, por fabor.','Call an ambulance, please.','Yama ambulans, por fabor.'],
['p040','nl-NL','Dutch','Goedemorgen.','Good morning.','Goedemorgen.'],['p041','nl-NL','Dutch','Dank u.','Thank you.','Dank u.'],['p042','nl-NL','Dutch','Alstublieft.','Please.','Alstublieft.'],['p043','nl-NL','Dutch','Waar is de uitgang?','Where is the exit?','Waar is de uitgang?'],
['p044','es-ES','Spanish','Buenos dias.','Good morning.','Buenos dias.'],['p045','es-ES','Spanish','Por favor.','Please.','Por favor.'],['p046','es-ES','Spanish','Gracias.','Thank you.','Gracias.'],['p047','es-ES','Spanish','Que recomienda?','What do you recommend?','Que recomienda?']
];
const P=raw.map(x=>({id:x[0],lang:x[1],cat:x[2],pap:x[3],eng:x[4],speak:x[5]}));
const L=[['Greetings',['p001','p002','p003','p004','p005']],['Polite Survival',['p006','p007','p008','p009','p010']],['Airport',['p011','p012','p013','p014']],['Taxi',['p015','p016','p017','p018','p019','p020']],['Hotel',['p021','p022','p023','p024']],['Dining',['p025','p026','p027','p028','p029']],['Drinks',['p030','p031','p032']],['Beach',['p033','p034','p035']],['Birthday',['p036']],['Emergency',['p037','p038','p039']],['Dutch Basics',['p040','p041','p042','p043']],['Spanish Basics',['p044','p045','p046','p047']]];while(L.length<40)L.push(['Review '+(L.length+1),L[L.length%12][1]]);
const scenarios=[['Airport Arrival',['Airport','Polite','Taxi']],['Hotel and Concierge',['Hotel','Polite','Emergency']],['Drinks and Dining',['Restaurant','Drinks','Polite']],['Taxi and Directions',['Taxi']],['Beach and Excursions',['Beach']],['Birthday Mode',['Birthday']],['Emergency Calm Mode',['Emergency','Dutch','Spanish']]];
let mode=localStorage.mode||'slow',lesson=0,step=0,auto=false,busy=false,score=0;const $=id=>document.getElementById(id), p=id=>P.find(x=>x.id===id)||P[0];
function status(t){$('status').textContent=t} function cap(s){return s[0].toUpperCase()+s.slice(1)}
function setMode(m){mode=m;localStorage.mode=m;['slow','normal','local'].forEach(x=>$('sp'+cap(x)).classList.toggle('active',x===m));status('Speed set to '+m)}
function wait(ms){return new Promise(r=>setTimeout(r,ms))}
function speechLang(lang){return lang==='pap'?'es-ES':lang}
function voiceFor(lang){const wanted=speechLang(lang);const vs=speechSynthesis.getVoices();return vs.find(v=>v.lang===wanted)||vs.find(v=>v.lang&&v.lang.toLowerCase().startsWith(wanted.split('-')[0].toLowerCase()))||vs.find(v=>v.lang==='es-ES')||vs.find(v=>v.lang==='en-US')||vs[0]}
function speak(text,rate=.55,lang='en-US'){return new Promise(res=>{if(!window.speechSynthesis){res();return}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.rate=rate;u.lang=speechLang(lang);let v=voiceFor(lang);if(v)u.voice=v;u.onend=res;u.onerror=res;status('Playing '+(lang==='pap'?'Spanish voice for Papiamentu':speechLang(lang))+'...');speechSynthesis.speak(u)})}
function mp3(src){return new Promise(res=>{let a=new Audio(src);a.onplay=()=>status('Playing native audio...');a.onended=()=>res(true);a.onerror=()=>res(false);a.play().catch(()=>res(false))})}
async function playPhrase(q){if(busy)return;busy=true;let slow=mode==='slow';let ok=await mp3(`audio/${q.id}_${slow?'slow':'normal'}.mp3`);if(!ok){await speak(q.speak,slow?.52:mode==='normal'?.72:.9,q.lang)}if(mode==='slow'){await wait(900);ok=await mp3(`audio/${q.id}_slow.mp3`);if(!ok)await speak(q.speak,.52,q.lang);await wait(800);await speak(q.eng,.62,'en-US');await wait(600);await speak('Your turn. Repeat it now.',.58,'en-US')}else if(mode==='normal'){await wait(450);await speak(q.eng,.72,'en-US')}busy=false}
async function playCurrent(){await playPhrase(p(L[lesson][1][step]));if(auto&&step<L[lesson][1].length-1){step++;renderPlayer();setTimeout(playCurrent,800)}else if(auto){auto=false;status('Lesson complete.')}}
function renderTabs(){ $('tabs').innerHTML=tabs.map(([id,label])=>`<button class="tab ${id==='coach'?'active':''}" onclick="show('${id}',this)">${label}</button>`).join('') }
function show(id,el){document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));if(el)el.classList.add('active');if(id==='quiz')quiz()}
function card(q){return `<div class="phrase"><div class="pap">${q.pap}</div><div class="eng">${q.eng}</div><div class="sound">Voice route: ${q.lang==='pap'?'Spanish voice for Papiamentu':q.lang}</div><div class="note">Native: audio/${q.id}_normal.mp3 / audio/${q.id}_slow.mp3</div><div class="row"><button class="btn" onclick='playPhrase(${JSON.stringify(q)})'>Coach</button><button class="btn secondary" onclick='speak(${JSON.stringify(q.speak)},.52,${JSON.stringify(q.lang)})'>Pronounce</button></div></div>`}
function renderCoach(){ $('coach').innerHTML=`<div class="card"><h2>Choose a trip scenario</h2><p class="big">Papiamentu now uses the Spanish system voice and reads the real phrase. Native MP3s still override everything when uploaded.</p></div><div class="grid scenario-grid">${scenarios.map((s,i)=>`<div class="card"><h3>${s[0]}</h3><p>${s[1].join(', ')}</p><button class="btn" onclick="openScenario(${i})">Open</button></div>`).join('')}</div><div id="scenarioDetail"></div>` }
function openScenario(i){let cats=scenarios[i][1],list=P.filter(q=>cats.includes(q.cat));$('scenarioDetail').innerHTML=`<div class="card"><h2>${scenarios[i][0]}</h2>${list.map(card).join('')}</div>`;$('scenarioDetail').scrollIntoView({behavior:'smooth'})}
function renderLessons(){ $('lessons').innerHTML=`<div class="card"><h2>40 Lesson Player</h2><p class="big">Use Start for auto-advance. Use Repeat / Next / Previous any time.</p></div><div class="grid">${L.map((l,i)=>`<div class="card"><h3>Lesson ${i+1}: ${l[0]}</h3><p>${l[1].map(id=>p(id).pap).slice(0,3).join(' · ')}</p><button class="btn" onclick="openLesson(${i})">Open</button> <button class="btn secondary" onclick="startLesson(${i})">Start</button></div>`).join('')}</div><div id="player"></div>` }
function openLesson(i){lesson=i;step=0;auto=false;renderPlayer();$('player').scrollIntoView({behavior:'smooth'})}
function startLesson(i){lesson=i;step=0;auto=true;renderPlayer();playCurrent();$('player').scrollIntoView({behavior:'smooth'})}
function renderPlayer(){let ids=L[lesson][1],q=p(ids[step]);$('player').innerHTML=`<div class="card"><h2>Lesson ${lesson+1}: ${L[lesson][0]}</h2><div class="playerBox"><span class="pill">Phrase ${step+1} of ${ids.length}</span><div class="pap">${q.pap}</div><div class="eng">${q.eng}</div><div class="sound">Voice route: ${q.lang==='pap'?'Spanish voice for Papiamentu':q.lang}</div><div class="row"><button class="btn secondary" onclick="prev()">Previous</button><button class="btn" onclick="playCurrent()">Repeat</button><button class="btn secondary" onclick="next()">Next</button><button class="btn ${auto?'red':'green'}" onclick="toggleAuto()">${auto?'Stop Auto':'Auto-Advance'}</button></div></div>${ids.map((id,n)=>`<div class="phrase ${n===step?'current':''}"><b>${n+1}.</b> ${p(id).pap}<div class="eng">${p(id).eng}</div></div>`).join('')}</div>`}
function next(){step=Math.min(L[lesson][1].length-1,step+1);renderPlayer()} function prev(){step=Math.max(0,step-1);renderPlayer()} function toggleAuto(){auto=!auto;renderPlayer();if(auto)playCurrent()}
function renderPhrasebook(f=''){let q=f.toLowerCase(),list=P.filter(x=>(x.cat+x.pap+x.eng+x.speak+x.lang).toLowerCase().includes(q));$('phrasebook').innerHTML=`<div class="card"><h2>Phrasebook</h2><input class="search" value="${f}" placeholder="Search taxi, drink, Dutch, Spanish..." oninput="renderPhrasebook(this.value)"></div>${list.map(card).join('')}`}
function quiz(){let q=P[Math.floor(Math.random()*P.length)],opts=[q.eng,...P.filter(x=>x!==q).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.eng)].sort(()=>Math.random()-.5);$('quiz').innerHTML=`<div class="card"><h2>Quiz</h2>${card(q)}<div class="quizChoices">${opts.map(o=>`<button class="choice" onclick="this.classList.add('${o===q.eng?'correct':'wrong'}');${o===q.eng?'score++;setTimeout(quiz,900)':'speak(\'Try again\',.6,\'en-US\')'}">${o}</button>`).join('')}</div><p>Score: ${score}</p></div>`}
function renderNative(){ $('native').innerHTML=`<div class="card"><h2>Native Audio Upgrade</h2><p class="big">Routing is now: Papiamentu -> native MP3, then Spanish voice; Dutch -> nl-NL; Spanish -> es-ES; English -> en-US.</p></div>` }
function init(){renderTabs();renderCoach();renderLessons();renderPhrasebook();renderNative();$('unlockBtn').onclick=()=>speak('Audio is unlocked. Slow mode is on. Welcome to your Curacao language coach.',.52,'en-US');setMode(mode);if(window.speechSynthesis){speechSynthesis.onvoiceschanged=()=>speechSynthesis.getVoices()}}
init();