const tabs=[['home','Home'],['coach','Concierge'],['lessons','Lessons'],['rayna','Rayna Mode'],['sommelier','Wine'],['dessert','Desserts'],['drive','Driving'],['review','Review'],['quiz','Quiz']];
const phrases=[
['p001','pap','Basics','Bon dia.','Good morning.'],['p002','pap','Basics','Bon tardi.','Good afternoon.'],['p003','pap','Basics','Kon ta bai?','How are you?'],['p004','pap','Basics','Mi ta bon.','I am good.'],['p005','pap','Polite','Por fabor.','Please.'],['p006','pap','Polite','Danki.','Thank you.'],['p007','pap','Polite','Bo por ripiti?','Can you repeat?'],
['p010','pap','Airport','Mi tin un reservashon.','I have a reservation.'],['p011','pap','Airport','Mi ta buska un taxi.','I am looking for a taxi.'],['p012','pap','Taxi','Kuantu e ta kusta?','How much does it cost?'],['p013','pap','Taxi','Llevami na hotel.','Take me to the hotel.'],['p014','pap','Taxi','Na man drechi.','Right.'],['p015','pap','Taxi','Na man robes.','Left.'],
['p020','pap','Hotel','Mi nomber ta Rayna.','My name is Rayna.'],['p021','pap','Hotel','Bo por yuda mi?','Can you help me?'],['p022','pap','Hotel','Mi tin un problema.','I have a problem.'],['p023','pap','Hotel','Mi a papia ku e concierge team.','I spoke with the concierge team.'],
['p030','pap','Restaurant','Nos tin un reservashon.','We have a reservation.'],['p031','pap','Restaurant','Kiko bo ta rekomenda?','What do you recommend?'],['p032','pap','Restaurant','La cuenta, por fabor.','The bill, please.'],
['p040','pap','Wine','Mi ta buska un bon Cabernet Sauvignon.','I am looking for a good Cabernet Sauvignon.'],['p041','pap','Wine','Bo tin Cabernet Sauvignon di Napa Valley?','Do you have Cabernet Sauvignon from Napa Valley?'],['p042','pap','Wine','Bo tin Caymus?','Do you have Caymus?'],['p043','pap','Wine','Kua Cabernet bo ta rekomenda?','Which Cabernet do you recommend?'],['p044','pap','Wine','Mi ke un glas Cabernet Sauvignon, por fabor.','I would like a glass of Cabernet Sauvignon, please.'],['p045','pap','Wine','Mi ke un botella di Cabernet Sauvignon.','I would like a bottle of Cabernet Sauvignon.'],['p046','pap','Wine','Esaki ta seko of dushi?','Is this dry or sweet?'],
['p050','pap','Cocktails','Mi ke un Hugo Spritz ku hopi mint, por fabor.','I would like a Hugo Spritz with lots of mint, please.'],['p051','pap','Cocktails','Bo por pone mas mint aden?','Can you add extra mint?'],['p052','pap','Cocktails','Mi ke un French 79, por fabor.','I would like a French 79, please.'],['p053','pap','Cocktails','Kua cocktail bo ta rekomenda?','Which cocktail do you recommend?'],
['p060','pap','Dessert','Kiko postre bo tin awe?','What desserts do you have today?'],['p061','pap','Dessert','Kiko postre bo ta rekomenda?','What dessert do you recommend?'],['p062','pap','Dessert','Kua ta bo postre mas popular?','What is your most popular dessert?'],['p063','pap','Dessert','Mi ta gusta chokolati.','I like chocolate.'],['p064','pap','Dessert','Mi ta gusta postrenan ku karamel.','I like desserts with caramel.'],['p065','pap','Dessert','Bo tin cheesecake?','Do you have cheesecake?'],['p066','pap','Dessert','Bo tin gelato?','Do you have gelato?'],['p067','pap','Dessert','Mi ke comparti un postre ku mi famia.','I would like to share a dessert with my family.'],['p068','pap','Dessert','Kua bin bo ta rekomenda ku e postre aki?','Which wine do you recommend with this dessert?'],['p069','pap','Dessert','Esaki ta bai bon ku Cabernet Sauvignon?','Does this pair well with Cabernet Sauvignon?'],
['p070','pap','Birthday','Nos ta selebra cumpleano di mi yiu Riley ku ta bira 11.','We are celebrating my daughter Riley turning 11.'],['p071','pap','Birthday','Nos ta selebra cumpleano di mi sobrina Harper ku ta bira 10.','We are celebrating my niece Harper turning 10.'],['p072','pap','Birthday','Felis cumpleano, Ry Ry.','Happy birthday, Ry Ry.'],['p073','pap','Birthday','Nos ke dekorashon den kamber.','We want decorations in the room.'],['p074','pap','Photo','Nos ta tuma potret di famia na Director Beach.','We are taking family photos at Director Beach.'],
['p080','pap','Beach','Nos tin les di mermaid na dies or di mainta.','We have mermaid lessons at 10 in the morning.'],['p081','pap','Beach','Nos tin un les di snorkel na Playa Piskado.','We have a snorkeling lesson at Playa Piskado.'],['p082','pap','Beach','Silla di playa.','Beach chair.'],['p083','pap','Beach','Sombre.','Umbrella.'],
['p090','pap','Emergency','Mi tin dolor.','I have pain.'],['p091','pap','Emergency','Mi mester un dokter.','I need a doctor.'],['p092','pap','Emergency','Mi a perde mi pasaporte.','I lost my passport.'],['p093','pap','Emergency','Yama ambulans, por fabor.','Call an ambulance, please.'],['p094','pap','Emergency','Mi no por haya mi yiu.','I cannot find my child.'],
['d001','nl-NL','Dutch','Goedemorgen.','Good morning.'],['d002','nl-NL','Dutch','Dank u.','Thank you.'],['d003','nl-NL','Dutch','Alstublieft.','Please.'],['d004','nl-NL','Dutch','Waar is de uitgang?','Where is the exit?'],['s001','es-ES','Spanish','Buenos dias.','Good morning.'],['s002','es-ES','Spanish','Por favor.','Please.'],['s003','es-ES','Spanish','Gracias.','Thank you.'],['s004','es-ES','Spanish','Que recomienda?','What do you recommend?']
].map(x=>({id:x[0],lang:x[1],cat:x[2],pap:x[3],eng:x[4]}));
const lessons=[['Travel Basics',['p001','p002','p003','p004','p005','p006','p007']],['Airport and Taxi',['p010','p011','p012','p013','p014','p015']],['Hotel Concierge',['p020','p021','p022','p023']],['Restaurants',['p030','p031','p032']],['Cabernet and Wine',['p040','p041','p042','p043','p044','p045','p046']],['Cocktails',['p050','p051','p052','p053']],['Desserts',['p060','p061','p062','p063','p064','p065','p066','p067','p068','p069']],['Riley Birthday',['p070','p071','p072','p073','p074']],['Beach and Mermaid',['p080','p081','p082','p083']],['Emergency Survival',['p090','p091','p092','p093','p094']],['Dutch Companion',['d001','d002','d003','d004']],['Spanish Companion',['s001','s002','s003','s004']]];
while(lessons.length<40)lessons.push(['Review '+(lessons.length+1),lessons[lessons.length%12][1]]);
const scenarios=[['Luxury Hotel Check-In',['p001','p020','p023','p021','p022']],['Wine at Dinner',['p040','p041','p042','p043','p044','p045']],['Cocktail Order',['p050','p051','p052','p053']],['Dessert Decision',['p060','p061','p062','p063','p067','p068','p069']],['Birthday Concierge',['p070','p071','p073','p074']],['Beach Day',['p080','p081','p082','p083']],['Emergency Calm',['p090','p091','p092','p093','p094']]];
let state=JSON.parse(localStorage.curacaoPremium||'{"xp":0,"streak":0,"mastered":[],"hard":[]}');let mode=localStorage.mode||'slow',lesson=0,step=0,auto=false,busy=false,score=0;const $=id=>document.getElementById(id), by=id=>phrases.find(p=>p.id===id)||phrases[0];
function save(){localStorage.curacaoPremium=JSON.stringify(state)}function status(t){$('status').textContent=t}function cap(s){return s[0].toUpperCase()+s.slice(1)}
function setMode(m){mode=m;localStorage.mode=m;['slow','normal','local'].forEach(x=>{let e=$('sp'+cap(x));if(e)e.classList.toggle('active',x===m)});status('Speed set to '+m)}
function wait(ms){return new Promise(r=>setTimeout(r,ms))}function speechLang(l){return l==='pap'?'es-ES':l}
function voiceFor(l){let wanted=speechLang(l);let vs=speechSynthesis.getVoices();return vs.find(v=>v.lang===wanted)||vs.find(v=>v.lang&&v.lang.toLowerCase().startsWith(wanted.split('-')[0].toLowerCase()))||vs.find(v=>v.lang==='es-ES')||vs.find(v=>v.lang==='en-US')||vs[0]}
function speak(text,rate=.55,lang='en-US'){return new Promise(res=>{if(!window.speechSynthesis){res();return}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.rate=rate;u.lang=speechLang(lang);let v=voiceFor(lang);if(v)u.voice=v;u.onend=res;u.onerror=res;status('Playing '+(lang==='pap'?'Spanish voice for Papiamentu':speechLang(lang))+'...');speechSynthesis.speak(u)})}
function mp3(src){return new Promise(res=>{let a=new Audio(src);a.onplay=()=>status('Playing native audio...');a.onended=()=>res(true);a.onerror=()=>res(false);a.play().catch(()=>res(false))})}
async function playPhrase(q){if(busy)return;busy=true;let slow=mode==='slow';let ok=await mp3(`audio/${q.id}_${slow?'slow':'normal'}.mp3`);if(!ok)await speak(q.pap,slow?.52:mode==='normal'?.72:.92,q.lang);if(mode==='slow'){await wait(800);ok=await mp3(`audio/${q.id}_slow.mp3`);if(!ok)await speak(q.pap,.52,q.lang);await wait(700);await speak(q.eng,.62,'en-US');await wait(500);await speak('Your turn. Repeat it now.',.58,'en-US')}else if(mode==='normal'){await wait(350);await speak(q.eng,.72,'en-US')}state.xp+=2;if(!state.mastered.includes(q.id))state.hard=[...new Set([...(state.hard||[]),q.id])];save();renderHomeMini();busy=false}
async function playCurrent(){await playPhrase(by(lessons[lesson][1][step]));if(auto&&step<lessons[lesson][1].length-1){step++;renderPlayer();setTimeout(playCurrent,700)}else if(auto){auto=false;state.streak++;state.xp+=10;save();status('Lesson complete. XP added.');renderPlayer()}}
function renderTabs(){ $('tabs').innerHTML=tabs.map(([id,label])=>`<button class="tab ${id==='home'?'active':''}" onclick="show('${id}',this)">${label}</button>`).join('')}
function show(id,el){document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));if(el)el.classList.add('active');if(id==='quiz')quiz();if(id==='review')renderReview()}
function renderHomeMini(){let e=$('homeStats');if(e)e.innerHTML=`<span class="pill">XP ${state.xp||0}</span><span class="pill">Streak ${state.streak||0}</span><span class="pill">Mastered ${(state.mastered||[]).length}</span><span class="pill">Review ${(state.hard||[]).length}</span>`}
function card(q){return `<div class="phrase"><div class="pap">${q.pap}</div><div class="eng">${q.eng}</div><div class="sound">Voice route: ${q.lang==='pap'?'Spanish voice for Papiamentu':q.lang}</div><div class="note">Native: audio/${q.id}_normal.mp3 / audio/${q.id}_slow.mp3</div><div class="row"><button class="btn" onclick='playPhrase(${JSON.stringify(q)})'>Coach</button><button class="btn secondary" onclick='markHard(${JSON.stringify(q.id)})'>Review</button><button class="btn green" onclick='markMastered(${JSON.stringify(q.id)})'>Mastered</button></div></div>`}
function markHard(id){state.hard=[...new Set([...(state.hard||[]),id])];save();status('Added to review.')}function markMastered(id){state.mastered=[...new Set([...(state.mastered||[]),id])];state.hard=(state.hard||[]).filter(x=>x!==id);state.xp+=5;save();renderHomeMini();status('Marked mastered. +5 XP')}
function renderHome(){ $('home').innerHTML=`<div class="card"><h2>Premium Curaçao Coach</h2><p class="big">Concierge role-play, wine, cocktails, desserts, Rayna Mode, driving mode, spaced review, XP, and native-audio readiness.</p><div id="homeStats"></div></div><div class="grid"><div class="card"><h3>Today</h3><p>Start with Rayna Mode, Wine, or Dessert before dinner.</p><button class="btn" onclick="show('rayna')">Open Rayna Mode</button></div><div class="card"><h3>Driving Mode</h3><p>Hands-light call-and-response practice.</p><button class="btn secondary" onclick="show('drive')">Start Driving</button></div></div>`;renderHomeMini()}
function renderCoach(){ $('coach').innerHTML=`<div class="card"><h2>Concierge Role-Play</h2><p class="big">Choose a scenario. The coach plays a guided interaction and pauses for you.</p></div><div class="grid scenario-grid">${scenarios.map((s,i)=>`<div class="card"><h3>${s[0]}</h3><p>${s[1].map(id=>by(id).pap).slice(0,3).join(' · ')}</p><button class="btn" onclick="openScenario(${i})">Open</button><button class="btn secondary" onclick="playScenario(${i})">Coach</button></div>`).join('')}</div><div id="scenarioDetail"></div>`}
function openScenario(i){let ids=scenarios[i][1];$('scenarioDetail').innerHTML=`<div class="card"><h2>${scenarios[i][0]}</h2>${ids.map(id=>card(by(id))).join('')}</div>`;$('scenarioDetail').scrollIntoView({behavior:'smooth'})}
async function playScenario(i){for(const id of scenarios[i][1]){await playPhrase(by(id));await wait(700)}}
function renderLessons(){ $('lessons').innerHTML=`<div class="card"><h2>40 Lesson Player</h2><p class="big">Auto-advance, repeat, next, previous, and progress tracking.</p></div><div class="grid">${lessons.map((l,i)=>`<div class="card"><h3>Lesson ${i+1}: ${l[0]}</h3><p>${l[1].map(id=>by(id).pap).slice(0,3).join(' · ')}</p><button class="btn" onclick="openLesson(${i})">Open</button><button class="btn secondary" onclick="startLesson(${i})">Start</button></div>`).join('')}</div><div id="player"></div>`}
function openLesson(i){lesson=i;step=0;auto=false;renderPlayer();$('player').scrollIntoView({behavior:'smooth'})}function startLesson(i){lesson=i;step=0;auto=true;renderPlayer();playCurrent();$('player').scrollIntoView({behavior:'smooth'})}
function renderPlayer(){let ids=lessons[lesson][1],q=by(ids[step]);$('player').innerHTML=`<div class="card"><h2>Lesson ${lesson+1}: ${lessons[lesson][0]}</h2><div class="playerBox"><span class="pill">Phrase ${step+1} of ${ids.length}</span><div class="pap">${q.pap}</div><div class="eng">${q.eng}</div><div class="sound">Voice route: ${q.lang==='pap'?'Spanish voice for Papiamentu':q.lang}</div><div class="row"><button class="btn secondary" onclick="prev()">Previous</button><button class="btn" onclick="playCurrent()">Repeat</button><button class="btn secondary" onclick="next()">Next</button><button class="btn ${auto?'red':'green'}" onclick="toggleAuto()">${auto?'Stop Auto':'Auto-Advance'}</button></div></div>${ids.map((id,n)=>`<div class="phrase ${n===step?'current':''}"><b>${n+1}.</b> ${by(id).pap}<div class="eng">${by(id).eng}</div></div>`).join('')}</div>`}
function next(){step=Math.min(lessons[lesson][1].length-1,step+1);renderPlayer()}function prev(){step=Math.max(0,step-1);renderPlayer()}function toggleAuto(){auto=!auto;renderPlayer();if(auto)playCurrent()}
function listByCat(cat){return phrases.filter(p=>p.cat===cat).map(card).join('')}
function renderRayna(){ $('rayna').innerHTML=`<div class="card"><h2>Rayna Mode</h2><p class="big">Fast access for Cabernet, Caymus, Hugo Spritz, French 79, desserts, photos, birthday, concierge, and beach asks.</p></div>${['Wine','Cocktails','Dessert','Birthday','Photo','Hotel','Beach'].map(c=>`<div class="card"><h3>${c}</h3>${listByCat(c)}</div>`).join('')}`}
function renderSommelier(){ $('sommelier').innerHTML=`<div class="card"><h2>Sommelier Mode</h2><p class="big">Cabernet Sauvignon, Caymus, dry/sweet, bottle/glass, and pairing questions.</p></div>${listByCat('Wine')}`}
function renderDessert(){ $('dessert').innerHTML=`<div class="card"><h2>Dessert Mode</h2><p class="big">Ask about chocolate, caramel, cheesecake, gelato, sharing, and wine pairings.</p></div>${listByCat('Dessert')}`}
async function startDrive(){let ids=['p001','p003','p005','p006','p007','p011','p012','p020','p031','p040','p050','p060','p090'];for(const id of ids){await playPhrase(by(id));await wait(1100)}status('Driving session complete.')}function renderDrive(){ $('drive').innerHTML=`<div class="card"><h2>Pimsleur Driving Mode</h2><p class="big">Press start. Listen, repeat aloud, and let the coach move through key phrases.</p><button class="unlock" onclick="startDrive()">Start Driving Session</button></div>`}
function renderReview(){let ids=(state.hard||[]);$('review').innerHTML=`<div class="card"><h2>Spaced Review</h2><p class="big">These are phrases you marked for review.</p>${ids.length?ids.map(id=>card(by(id))).join(''):'<p>No review phrases yet.</p>'}</div>`}
function renderPhrasebook(f=''){let q=f.toLowerCase(),list=phrases.filter(x=>(x.cat+x.pap+x.eng+x.lang).toLowerCase().includes(q));$('phrasebook').innerHTML=`<div class="card"><h2>Phrasebook</h2><input class="search" value="${f}" placeholder="Search Cabernet, dessert, taxi..." oninput="renderPhrasebook(this.value)"></div>${list.map(card).join('')}`}
function quiz(){let q=phrases[Math.floor(Math.random()*phrases.length)],opts=[q.eng,...phrases.filter(x=>x!==q).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.eng)].sort(()=>Math.random()-.5);$('quiz').innerHTML=`<div class="card"><h2>Quiz</h2>${card(q)}<div class="quizChoices">${opts.map(o=>`<button class="choice" onclick="this.classList.add('${o===q.eng?'correct':'wrong'}');${o===q.eng?'score++;state.xp+=3;save();setTimeout(quiz,900)':'markHard(\''+q.id+'\');speak(\'Try again\',.6,\'en-US\')'}">${o}</button>`).join('')}</div><p>Score: ${score}</p></div>`}
function init(){renderTabs();renderHome();renderCoach();renderLessons();renderRayna();renderSommelier();renderDessert();renderDrive();renderPhrasebook();renderReview();$('unlockBtn').onclick=()=>speak('Audio is unlocked. Premium coach is ready.',.52,'en-US');setMode(mode);if(window.speechSynthesis){speechSynthesis.onvoiceschanged=()=>speechSynthesis.getVoices()}}
init();